version: '3.8'

services:
  react-app:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./react_app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production