image: node:18

services:
  - name: mongo:latest
    alias: mongo

variables:
  NODE_ENV: 'development'
  MONGO_URI: "mongodb://mongo:27017/testdb"

cache:
  key: node-modules
  paths:
    - backend/node_modules/
    - frontend/node_modules/

stages:
  - install
  - test

install_dependencies:
  stage: install
  script:
    - cd backend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - backend/node_modules/
      - frontend/node_modules/


test_backend:
  stage: test
  script:
    - cd backend
    - npm test
  dependencies:
    - install_dependencies

test_frontend:
  stage: test
  before_script:
    - mkdir -p frontend/.nyc_output
  script:
    - cd frontend
    - npm ci
    - npm run test
    - npm run test:coverage
  artifacts:
    paths:
      - frontend/coverage/src/coverage.svg
    expire_in: 1 week
  coverage: '/All files\s*\|\s*([\d]+(\.\d+)?)%/'
  dependencies:
    - install_dependencies





