image: node:18

services:
  mongo:
    image: mongo:latest
    alias: mongo

variables:
  NODE_ENV: 'development'
  MONGO_URI: "mongodb://mongo:27017/testdb"

cache:
  paths:
    - frontend/node_modules/
    - backend/node_modules/

stages:
  - install
  - test
  - lint
  - format
  - dependency-scanning

install_dependencies:
  stage: install
  script:
    - npm ci --prefix frontend
    - npm ci --prefix backend

wait_for_mongo:
  stage: test
  script:
    - echo "Warten auf MongoDB..."
    - until nc -z mongo 27017; do echo "MongoDB ist nicht verfügbar. Warte..."; sleep 1; done

test_backend:
  stage: test
  script:
    - npm test --prefix backend
  dependencies:
    - install_dependencies
    - wait_for_mongo

test_frontend:
  stage: test
  script:
    - npm test --prefix frontend
  dependencies:
    - install_dependencies

lint:
  stage: lint
  script:
    - npm run lint --prefix frontend
    - npm run lint --prefix backend
  dependencies:
    - install_dependencies

format:
  stage: format
  script:
    - npm run format --prefix frontend
    - npm run format --prefix backend
  dependencies:
    - install_dependencies

dependency_scanning:
  stage: dependency-scanning
  script:
    - echo "Dependency scanning wird hier konfiguriert"
  dependencies:
    - install_dependencies

include:
  - template: Security/SAST.gitlab-ci.yml
