image: node:18

services:
  - name: mongo:latest
    alias: mongo

variables:
  NODE_ENV: 'development'
  MONGO_URI: "mongodb://mongo:27017/testdb"

cache:
  key: node-modules
  paths:
    - backend/node_modules/

stages:
  - install
  - test

install_dependencies:
  stage: install
  script:
    - cd backend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - backend/node_modules/


test_backend:
  stage: test
  script:
    - cd backend
    - npm test